{% set name = "colima" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abiosoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e02f3abf3ad7911fe4665b1c3291f03677edc0efa93e8d37b337d76149a7202b

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/abiosoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  dev_url: https://github.com/abiosoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
