{% set name = "colima" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abiosoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 88e37091e64d632ec44e5284665e5adc6506000acb13102fa2bbc67790770a3d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/abiosoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  dev_url: https://github.com/abiosoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
