{% set name = "colima" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abiosoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c4a0f15f971d876ab4a725df802c7888abc73b9384c9df295c7e4ac888d276c5

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/abiosoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  dev_url: https://github.com/abiosoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
