{% set name = "colima" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abiosoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3e6d265378c1cfa17c8c041bcb1115e8ab02654756c327be258aff2276f2cf10

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/abiosoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  dev_url: https://github.com/abiosoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
