{% set name = "colima" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abiosoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2c0f670f2e3124d1e81894bc3c0bea90f25cc675bb293e70e8ff25f47c8db35e

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/abiosoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  dev_url: https://github.com/abiosoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
