schema_version: 1

context:
  version: "0.10.1"

package:
  name: colima
  version: ${{ version }}

source:
  url: https://github.com/abiosoft/colima/archive/v${{ version }}.tar.gz
  sha256: 9f115c628132bb73b3809a8037111f231863426fd2eeed782b61899823bd4783

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

tests:
  - script:
      - colima --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  homepage: https://github.com/abiosoft/colima
  repository: https://github.com/abiosoft/colima

extra:
  recipe-maintainers:
    - danielnachun
