schema_version: 1

context:
  version: "0.10.0"

package:
  name: colima
  version: ${{ version }}

source:
  url: https://github.com/abiosoft/colima/archive/v${{ version }}.tar.gz
  sha256: c91bdb0268b38bda95af2b29c6b7b3ee27e33c4c759efaa04d3f4ad8506dd3c5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - lima-vm

tests:
  - script:
      - colima --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Container runtimes on MacOS (and Linux) with minimal setup
  homepage: https://github.com/abiosoft/colima
  repository: https://github.com/abiosoft/colima

extra:
  recipe-maintainers:
    - danielnachun
